version: 2

jobs:
  build:
    docker:
      - image: elixir:1.5.2
    environment:
      MIX_ENV: test
    steps:
      - checkout
      - run:
          name: Install hex, rebar, and dependencies
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
      - restore_cache:
          keys:
            - cache-{{ arch }}-{{ checksum "mix.lock" }}-{{ checksum "mix.exs" }}
            - cache-{{ arch }}-{{ checksum "mix.lock" }}
            - cache-{{ arch }}
      - run:
          name: Test warning-free compilation
          command: |
            mix compile
            mix clean
            mix compile --warnings-as-errors
      - run:
          name: Dialyzer
          command: mix dialyzer --halt-exit-status
      - run:
          name: Credo
          command: mix credo
      - run:
          name: Elixir Tests
          command: mix test

      - save_cache:
          key: cache-{{ arch }}-{{ checksum "mix.lock" }}-{{ checksum "mix.exs" }}
          paths:
            - deps/
            - _build/test/