version: 2

jobs:
  build:
    docker:
      - image: elixir:1.5.2
    steps:
      - checkout
      - run:
          name: Install hex, rebar, and dependencies
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
      - restore_cache:
          keys:
            - deps-cache-{{ arch }}-{{ checksum "mix.lock" }}-{{ checksum "mix.exs" }}
            - deps-cache-{{ arch }}-{{ checksum "mix.lock" }}
      - restore_cache:
          keys:
            - build-cache-{{ arch }}-{{ checksum "mix.lock" }}-{{ checksum "mix.exs" }}
            - build-cache-{{ arch }}-{{ checksum "mix.lock" }}
      - run:
          name: Test warning-free compilation
          command: |
            mix compile
            mix clean
            mix compile --warnings-as-errors
      - run:
          name: Dialyzer
          command: mix dialyzer --halt-exit-status
      - run:
          name: Credo
          command: mix credo --strict
      - run:
          name: Elixir Tests
          command: mix test

      - save_cache:
          key: deps-cache-{{ arch }}-{{ checksum "mix.lock" }}-{{ checksum "mix.exs" }}
          paths:
            - deps/
      - save_cache:
          key: deps-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - deps/
      - save_cache:
          key: build-cache-{{ arch }}-{{ checksum "mix.lock" }}-{{ checksum "mix.exs" }}
          paths:
            - _build/test/
      - save_cache:
          key: build-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build/test/